name: Python CI

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install boto3
        run: pip install boto3

      - name: Run script
        run: python s3.py
